### ISSUE TITLE
Some questions about StartingPosition.h

### ISSUE THREAD

**Issue by nanyangnuan** [danisotelo/qm_door#1]
Hi! Thank you for sharing the project!
I have some questions about StartingPosition.h. Can you tell me what the parameters 
ARM_DIST ,  HEIGHT ,  ARM_HEIGHT ,  THRESHOLD mean? It will be very helpful to me.
![image](https://github.com/user-attachments/assets/32dadeae-a853-43ca-89b8-4b2df255f12b)

**Comment by danisotelo** [comment]
Hi @nanyangnuan! I created this file to substitute the need in the repository of Skywoodsz of modifying these values manually in several files related to the controller. These parameters are mainly used by the trajectories publisher:

- `ARM_DIST` is the desired distance between the base centroid and the end-effector position in the XY plane.
- `HEIGHT` is defined in `reference.info` as `comHeight` but I also included it here to have it all together (they should be the same) and is the height of the base centroid with respect to the ground.
- `ARM_HEIGHT` corresponds to the height difference between the end-effector and the base centroid (I copied this value from the original repository).
- `THRESHOLD` was a value I introduced while writting the planner code but it is no longer used in the current code. I used it to set the distance between the target and the current position for which a position is considered to be reached.

**Comment by nanyangnuan** [comment]
@danisotelo 
Thank you for your reply. But I still have some issues during the operation. After running rviz for a while, rviz will suddenly crash, and your program and skywoodsz/qm_control will also experience this issue. The memory capacity is sufficient. Have you ever experienced a similar phenomenon? If so, how was it resolved? This will be very helpful to me.
![image](https://github.com/user-attachments/assets/04b4b332-3bc8-4f72-90d8-bfc608d6b6ed)

**Comment by danisotelo** [comment]
I have never encountered that issue before 🤔. Maybe it's due to some necessary dependencies for RViz you don't have or that your version is not up to date. Maybe you can try reinstalling RViz, a fresh installation may resolve hidden issues. Also you can try running RViz in debug mode to get more detailed logs that might point to the specific point of the crash.

**Comment by LianzhaoZhang** [comment]
> Hi @nanyangnuan! I created this file to substitute the need in the repository of Skywoodsz of modifying these values manually in several files related to the controller. These parameters are mainly used by the trajectories publisher:
> 
> * `ARM_DIST` is the desired distance between the base centroid and the end-effector position in the XY plane.
> * `HEIGHT` is defined in `reference.info` as `comHeight` but I also included it here to have it all together (they should be the same) and is the height of the base centroid with respect to the ground.
> * `ARM_HEIGHT` corresponds to the height difference between the end-effector and the base centroid (I copied this value from the original repository).
> * `THRESHOLD` was a value I introduced while writting the planner code but it is no longer used in the current code. I used it to set the distance between the target and the current position for which a position is considered to be reached.

I encountered a similar issue. After running `load_qm_target.launch`, an Interactive Marker appears in Rviz. If I right-click on the Interactive Marker without first moving it, Rviz crashes. I suspect this might be due to some parameters not being initialized. However, since this issue doesn’t impact my ability to learn from the project, I haven't taken steps to resolve it yet.
